# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vote_count', models.IntegerField()),
            ],
            options={
                'ordering': ['vote_count'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('entry_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Category'),
        ),
    ]
